const msg_it = {
  it: {
    words: {
      da: 'dal',
      a: 'al',
    },
    home: {
      guida: 'Guida',
      guida_passopasso: 'Guida Passo Passo',
    },
    grid: {
      editvalues: 'Modifica Valori',
      addrecord: 'Aggiungi Riga',
      showprevedit: 'Mostra Eventi Passati',
      columns: 'Colonne',
      tableslist: 'Tabelle',
      nodata: 'Nessun Dato',
    },
    gallery: {
      author_username: 'Utente',
      title: 'Titolo',
      directory: 'Directory',
      list: 'Lista',
    },
    profile: {
      chisei: 'Chi Sei? Raccontaci di te:',
      iltuoimpegno: 'Quale è stato il tuo impegno per salvare il pianeta ad oggi?',
      come_aiutare: 'Cosa vorresti fare per aiutare il pianeta?',
    },
    otherpages: {
      sito_offline: 'Sito in Aggiornamento',
      modifprof: 'Modifica Profilo',
      biografia: 'Biografia',
      update: 'Aggiornamento in Corso...',
      error404: 'error404',
      error404def: 'error404def',
      admin: {
        menu: 'Amministrazione',
        eventlist: 'Le tue Prenotazioni',
        usereventlist: 'Prenotazioni Utenti',
        userlist: 'Lista Utenti',
        zoomlist: 'Calendario Zoom',
        extralist: 'Lista Extra',
        dbop: 'Db Operations',
        tableslist: 'Lista Tabelle',
        navi: 'Navi',
        listadoni_navi: 'Lista Doni Navi',
        newsletter: 'Newsletter',
        pages: 'Pagine',
        media: 'Media',
        gallery: 'Gallerie',
        listaflotte: 'Flotte',
      },
      manage: {
        menu: 'Gestione',
        manager: 'Gestore',
        nessuno: 'Nessuno',
        sendpushnotif: 'Invia Msg Push',
      },
      messages: {
        menu: 'I tuoi Messaggi',
      },
    },
    sendmsg: {
      write: 'scrive',
    },
    stat: {
      imbarcati: 'Imbarcati',
      imbarcati_weekly: 'Imbarcati Settimanali',
      imbarcati_in_attesa: 'Imbarcati in Attesa',
      qualificati: 'Qualificati con almeno 2 invitati',
      requisiti: 'Utenti con i 7 Requisiti',
      zoom: 'Partecipato in Zoom',
      modalita_pagamento: 'Modalità di Pagamento Inseriti',
      accepted: 'Accettato Linee Guida + Video',
      dream: 'Hanno scritto il Sogno',
      email_not_verif: 'Email non Verificate',
      telegram_non_attivi: 'Telegram Non Attivi',
      telegram_pendenti: 'Telegram Pendenti',
      reg_daily: 'Registrazioni Giornaliere',
      reg_weekly: 'Registrazioni Settimanali',
      reg_total: 'Registrazioni Totali',
    },
    steps: {
      nuovo_imbarco: 'Prenota un altro Viaggio',
      vuoi_entrare_nuova_nave: 'Desideri aiutare il Movimento ad avanzare e intendi entrare in un\'altra Nave?<br>Effettuando un Nuovo Dono di 33€, potrai percorrere un altro viaggio ed avere un\'altra opportunità di diventare Sognatore!<br>'
      + 'Se confermi verrai aggiunto alla lista d\'attesa per i prossimi imbarchi.',
      inserisci_invitante: 'Inserisci qui sotto l\'username della persona che vuoi aiutare, donandoti come suo Invitato:',
      vuoi_cancellare_imbarco: 'Sicuro di voler cancellare questo imbarco in Nave AYNI?',
      sei_stato_aggiunto: 'Sei stato aggiunto alla lista d\'imbarco! Nei prossimi giorni verrai aggiunto ad una Nuova Nave in partenza!',
      completed: 'Completati',
      passi_su: '{passo} passi su {totpassi}',
      video_intro_1: '1. Benvenuti in {sitename}',
      video_intro_2: '2. Nascita di {sitename}',
      read_guidelines: 'Ho letto ed Accetto queste condizioni scritte qui sopra',
      saw_video_intro: 'Dichiaro di aver visto i Video',
      paymenttype: 'Modalità di Pagamento (Revolut)',
      paymenttype_long: 'I <strong>metodi di Pagamento sono: <ul><li><strong style="font-size: 1.25rem; color: green; background-color: yellow;">Revolut</strong> (ALTAMENTE CONSIGLIATA):<br>la Carta Prepagata Revolut con IBAN Inglese, trasferimenti gratuiti, più libera e semplice da utilizzare. Disponibile l\'app per il cellulare.</li><br><li><strong>Paypal</strong> perchè è un sistema molto diffuso in tutta Europa (il trasferimento e gratuito) e si possono collegare le carte prepagate, le carte di credito e il conto corrente <strong>SENZA COMMISSIONI</strong>. In questo modo non dovrai condividere i numeri delle tue carte o del c/c ma solo la mail che avrai usato in fase di iscrizione su Paypal. Disponibile l\'app per il cellulare. <br><br><span style="font-style: italic; font-size: 1rem; color:red;"><strong>NOTA BENE</strong>: Ultimamente Paypal sta avendo problemi perchè tendono a bloccare i soldi sul conto del Sognatore per 6 mesi per controlli, quindi da utilizzare SOLO se impossiblitati ad aprire un conto con Revolut.</span></li></ul>',
      paymenttype_long2: 'Si consiglia di avere a disposizione <strong>almeno 2 Modalità di Pagamento</strong>, per scambiarsi i doni.',
      paymenttype_paypal: 'Come Aprire un conto Paypal (in 2 minuti)',
      paymenttype_paypal_carta_conto: 'Come associare una carta di Credito/Debito o un Conto Bancario su PayPal',
      paymenttype_paypal_link: 'Apri il Conto con Paypal',
      paymenttype_revolut: 'Come Aprire il conto con Revolut (in 2 minuti)',
      paymenttype_revolut_link: 'Apri il Conto con Revolut',
      entra_zoom: 'Entra in Zoom',
      linee_guida: 'Accetto le Linee Guida',
      video_intro: 'Vedo il Video',
      zoom: 'Partecipo ad almeno 1 Video-Conferenza',
      zoom_si_partecipato: 'Hai partecipato ad almeno 1 Video-Conferenza',
      zoom_partecipa: 'Partecipato ad almeno 1 Zoom',
      zoom_no_partecipato: 'Attualmente non hai ancora partecipato ad una Video-Conferenza (è un requisito per poter entrare)',
      zoom_long: 'Si richiede di partecipare ad almeno 1 Video-Conferenza, ma se sentirai che questi icontri sono anche un modo per condividere e stare in compagnia, allora potrai partecipare tutte le volte che lo desideri.<br><br><strong><br>Partecipando alle Video-Conferenze di Benvenuto lo Staff registrerà la vostra presenza <strong>ENTRO 24 ORE</strong>.</strong>',
      zoom_what: 'Tutorial come installare Zoom Cloud Meeting',
      // sharemovement_devi_invitare_almeno_2: 'Ancora non hai invitato 2 persone',
      // sharemovement_hai_invitato: 'Hai invitato almeno 2 persone',
      sharemovement_invitati_attivi_si: 'Hai almeno 2 persone invitate Attive',
      sharemovement_invitati_attivi_no: '<strong>Nota Bene:</strong>Le persone che hai invitato, per essere <strong>Attive</strong>, devono aver <strong>completato tutti i primi 7 Requisiti</strong> (vedi la tua <strong>Lavagna</strong> per capire cosa gli manca)',
      sharemovement: 'Condivido il Movimento',
      sharemovement_long: 'Condividi il Movimento {sitename} e invitali a partecipare agli Zoom di Benvenuto per entrare a far parte di questa grande Famiglia &#128516 .<br>',
      inv_attivi_long: '',
      enter_prog_completa_requisiti: 'Completa tutti i requisiti richiesti, per poter entrare nella Lista d\'imbarco.',
      enter_prog_requisiti_ok: 'Hai completato tutti i 7 requisiti per entrare nella Lista d\'Imbarco.<br>',
      enter_prog_msg: 'Riceverai un messaggio nei prossimi giorni su AYNI BOT, appena la tua Nave sarà pronta!',
      enter_prog_msg_2: 'Ricorda che più persone inviti e più sali di Posizione, per accedere alla prossima Nave!',
      enter_nave_9req_ok: 'COMPLIMENTI! Hai Completato TUTTI i 9 Passi della Guida! Grazie per Aiutare {sitename} ad Espandersi!<br>Potrai molto presto partire con il tuo Viaggio, facendo il tuo dono e proseguendo verso il Sognatore',
      enter_nave_9req_ko: 'Ricorda che puoi Aiutare a far Crescere ed Espandere il Movimento, Condividendo con chiunque questo nostro viaggio!',
      enter_prog: 'Entro nella Lista d\'Imbarco',
      enter_prog_long: 'Ricorda che puoi Aiutare a far Crescere ed Espandere il Movimento, Condividendo con chiunque questo nostro viaggio!<br>',
      collaborate: 'Collaborazione',
      collaborate_long: 'Continuo a collaborare con i miei compagni per arrivare al giorno in cui salperà la mia Nave.',
      dream: 'Scrivo il mio Sogno',
      dream_long: 'Scrivi qui il Sogno per il quale sei entrato in {sitename} e che desideri realizzare.<br>Sarà condiviso a quello di tutti gli altri per sognare insieme !',
      dono: 'Dono',
      dono_long: 'Faccio il mio dono nella data di partenza della mia Nave',
      support: 'Sostengo il movimento',
      support_long: 'Sostengo il movimento portando Energia, partecipando e organizzando Zoom, aiutando e informando i nuovi arrivati continuando a diffondere la visione di {sitename}',
      ricevo_dono: 'Ricevo il mio dono e CELEBRO',
      ricevo_dono_long: 'Evviva!!!<br><strong>QUESTO MOVIMENTO È REALE E POSSIBILE SE LO FACCIAMO FUNZIONARE TUTTI INSIEME !</strong>',
    },
    dialog: {
      continue: 'Continuare',
      close: 'Chiudi',
      copyclipboard: 'Copiato negli appunti',
      ok: 'Ok',
      yes: 'Si',
      no: 'No',
      delete: 'Elimina',
      cancel: 'Annulla',
      update: 'Aggiorna',
      add: 'Aggiungi',
      today: 'Oggi',
      book: 'Prenota',
      avanti: 'Avanti',
      indietro: 'Indietro',
      finish: 'Fine',
      sendmsg: 'Invia Messaggio',
      sendonlymsg: 'Invia solo un Msg',
      msg: {
        titledeleteTask: 'Elimina Task',
        deleteTask: 'Vuoi Eliminare {mytodo}?',
      },
    },
    comp: {
      Conta: 'Conta',
    },
    db: {
      recupdated: 'Record Aggiornato',
      recfailed: 'Errore durante aggiornamento Record',
      reccanceled: 'Annullato Aggiornamento. Ripristinato valore precendente',
      deleterecord: 'Elimina Record',
      deletetherecord: 'Eliminare il Record?',
      deletedrecord: 'Record Cancellato',
      recdelfailed: 'Errore durante la cancellazione del Record',
      duplicatedrecord: 'Record Duplicato',
      recdupfailed: 'Errore durante la duplicazione del Record',
    },
    components: {
      authentication: {
        telegram: {
          open: 'Clicca qui per aprire il BOT Telegram e segui le istruzioni',
          ifclose: 'Se non si apre Telegram cliccando sul bottone oppure l\'avevi eliminato, vai su Telegram e cerca \'{botname}\' dall\'icona della lente, poi premi Start e segui le istruzioni.',
          openbot: 'Apri \'{botname}\' su Telegram',
        },
        login: {
          facebook: 'Facebook',
        },
        email_verification: {
          title: 'Inizia la tua registrazione',
          introduce_email: 'inserisci la tua email',
          email: 'Email',
          invalid_email: 'La tua email è invalida',
          verify_email: 'Verifica la tua email',
          go_login: 'Torna al Login',
          incorrect_input: 'Inserimento incorretto.',
          link_sent: 'Apri la tua casella di posta, trova la email "Confermare la Registrazione: {sitename}" e clicca su "Verifica Registrazione"',
          se_non_ricevo: 'Se non ricevi la email, prova a controllare nella spam, oppure contattaci',
          title_unsubscribe: 'Disiscrizione alla newsletter',
          title_unsubscribe_done: 'Disiscrizione completata correttamente',
        },
      },
    },
    fetch: {
      errore_generico: 'Errore Generico',
      errore_server: 'Impossibile accedere al Server. Riprovare Grazie',
      error_doppiologin: 'Rieseguire il Login. Accesso aperto da un altro dispositivo.',
    },
    user: {
      notregistered: 'Devi registrarti al servizio prima di porter memorizzare i dati',
      loggati: 'Utente non loggato',
    },
    templemail: {
      subject: 'Oggetto Email',
      testoheadermail: 'Intestazione Email',
      content: 'Contenuto',
      img: 'Immagine 1',
      img2: 'Immagine 2',
      content2: 'Contenuto 2',
      options: 'Opzioni',
    },
    dashboard: {
      data: 'Data',
      data_rich: 'Data Rich.',
      ritorno: 'Ritorno',
      invitante: 'Invitante',
      dono_da_effettuare: 'Dono che dovrai effettuare',
      num_tessitura: 'Numero di Tessitura:',
      attenzione: 'Attenzione',
      downline: 'Invitati',
      downnotreg: 'Invitati non Registrati',
      notreg: 'Non Registrato',
      inv_attivi: 'Invitati con i 7 Requisiti',
      numinvitati: 'Almeno 2 Invitati',
      telefono_wa: 'Contatta su Whatsapp',
      sendnotification: 'Invia Notifica al Destinatario su Telegram BOT',
      ricevuto_dono: '😍🎊 Hai ricevuto in Regalo un Invitato {invitato} da parte di {mittente} !',
      ricevuto_dono_invitante: '😍🎊 Hai ricevuto in Regalo un Invitante da parte di {mittente} !',
      nessun_invitante: 'Nessun Invitante',
      nessun_invitato: 'Nessun Invitato',
      legenda_title: 'Clicca sul nome dell\'invitato per vedere lo stato dei suoi Requisiti.',
      nave_in_partenza: 'La Nave salperà il',
      nave_in_chiusura: 'Chiusura Gift Chat',
      nave_partita: 'Partita il',
      tutor: 'Tutor',
      traduttrici: 'Traduttrici',
      /*      sonomediatore: 'Quando diventi Meditore vieni contattato da un <strong>TUTOR</strong>, con lui devi:<br><ol class="lista">' +
      '<li>Aprire la tua <strong>Gift Chat</strong> (tu come proprietario e il Tutor ' +
      'come amministratore) con questo nome:<br><strong>{nomenave}</strong></li>' +
      '<li>Clicca sul nome della chat in alto -> Modifica -> Amministratori -> "Aggiungi Amministratore", seleziona il Tutor nell’elenco.</li>' +
      '<li>Devi configurare la chat in modo che chi entra vede anche i post precedenti (clicca sul nome della chat in alto, clicca su modifica, ' +
      'cambia la "cronologia per i nuovi membri" da nascosta a visibile.</li>' +
      '<li>Per trovare il <strong>link della Chat appena creata</strong>: clicca sul nome della chat in alto, clicca sulla Matita -> "Tipo di Gruppo" -> "invita nel gruppo tramite link", clicca su "copia link" e incollalo qui sotto, sulla casella <strong>"Link Gift Chat"</strong></li>' +
      '<li>Invia il Link della Gift Chat a tutti i Donatori, cliccando sul bottone qui sotto.</li></ol>',
*/
      sonomediatore: 'Quando sei MEDIATORE verrai contattato dai <strong>TUTOR AYNI</strong> tramite un messaggio sulla Chat <strong>AYNI BOT</strong> !',
      superchat: 'Nota Bene: Non inviarci la ricevuta, non ci occorre. Attendi il messaggio di conferma da parte del Sognatore (sulla Chat AYNI BOT).<br>SOLO se hai problemi di PAGAMENTO, o ti manca la conferma del SOGNATORE (dopo aver atteso almeno 12 ore) o se vuoi essere SOSTITUITO, due Tutor ti aspettano per aiutarti sulla Chat:<br><a href="{link_superchat}" target="_blank">Entra nella Gift Chat</a>',
      sonodonatore: '<ol class="lista"><li>Quando sei in questa posizione, verrai invitato (tramite un messaggio su <strong>AYNI BOT</strong>) ad effettuare il Dono. Non sarà più necessario entrare in una Chat.</li>'
      + '<li><strong>Avrai tempo 3 giorni per fare il Regalo</strong> (poi verrai sostituito), nella modalità di pagamento che troverai scritto sul messaggio in <strong>AYNI BOT</strong> .<br></ol>',
      sonodonatore_seconda_tessitura: '<ol class="lista"><li>Qui tu sei Mediatore e anche Donatore, ma essendo la seconda Tessitura (il Ritorno), non avrai bisogno di effettuare nuovamente il dono<br></ol>',
      controlla_donatori: 'Controlla Lista Donatori',
      link_chat: 'Link della Gift Chat Telegram',
      tragitto: 'Tragitto',
      nave: 'Nave',
      data_partenza: 'Data<br>Partenza',
      doni_inviati: 'Doni',
      nome_dei_passaggi: 'Nome<br>dei Passaggi',
      donatori: 'Donatori',
      donatore: 'Donatore',
      mediatore: 'Mediatore',
      sognatore: 'Sognatore',
      sognatori: 'SOGNATORI',
      intermedio: 'INTERMEDIO',
      pos2: 'Interm. 2',
      pos3: 'Interm. 3',
      pos5: 'Interm. 5',
      pos6: 'Interm. 6',
      gift_chat: 'Per entrare nella Gift Chat, clicca qui',
      quando_eff_il_tuo_dono: 'Quando effettuare il Regalo',
      entra_in_gift_chat: 'Entra in Gift Chat',
      invia_link_chat: 'Invia il Link della Gift Chat ai Donatori',
      inviare_msg_donatori: '5) Inviare messaggio ai Donatori',
      msg_donatori_ok: 'Inviato messaggio ai Donatori',
      metodi_disponibili: 'Metodi Disponibili',
      importo: 'Importo',
      effettua_il_dono: 'E\' arrivato il momento di Effettuare il proprio Dono al Sognatore<br><strong>👉 {sognatore} 👈</strong>  !<br><br>'
      + 'Inviare tramite <a href="https://www.paypal.com/" target="_blank">PayPal</a> a: <strong>{email}</strong><br>'
      + 'Aggiungere come messaggio la dicitura: <strong>Regalo</strong><br>'
      + '<strong><span style="color:red">ATTENZIONE IMPORTANTE:</span> Scegliere l\'opzione</strong><BR>"INVIO DI DENARO A UN AMICO"<br>Cosi non pagherai delle commissioni extra!',
      paypal_me: '<br>2) Metodo Semplificato<br><a href="{link_payment}" target="_blank">Cliccare direttamente qui</a><br>'
      + 'si aprirà PayPal con l\'importo e il destinatario gia impostato.<br>'
      + 'Aggiungere come messaggio la dicitura: <strong>Regalo</strong><br>'
      + '<strong><span style="color:red">ATTENZIONE IMPORTANTE:</span> TOGLIERE LA SPUNTA SU</strong>: Devi pagare beni o servizi? ... (Protezione acquisti Paypal)<br>Altrimenti pagherai inutilmente delle commissioni extra.<br>'
      + 'Se hai dubbi, guarda il video qui sotto per vedere come fare:<br>'
      + 'infine Clicca su “Invia Denaro ora”.',
      commento_al_sognatore: 'Scrivi qui un commento per il Sognatore:',
      qui_compariranno_le_info: 'Nel giorno della partenza della Nave, compariranno le informazioni del Sognatore',
      posizione: 'Posizione',
      come_inviare_regalo_con_paypal: 'Come Inviare il regalo tramite Paypal',
      ho_effettuato_il_dono: 'Ho effettuato il Dono',
      clicca_conferma_dono: 'Una volta inviato il Dono, lascia un commento al Sognatore e Clicca qui sotto per confermare che hai effettuato il tuo dono',
      fatto_dono: 'Hai confermato che il dono è stato Inviato',
      confermi_dono: 'Confermi che hai inviato il tuo Dono di 33€',
      dono_ricevuto: 'Il tuo Dono è stato Ricevuto!',
      dono_ricevuto_2: 'Ricevuto',
      dono_ricevuto_3: 'Arrivato!',
      confermi_dono_ricevuto: 'Confermi di aver ricevuto il Dono di 33€ da parte di {donatore}',
      confermi_dono_ricevuto_msg: 'Confermato di aver ricevuto il Dono di 33€ da parte di {donatore}',
      msg_bot_conferma: '{donatore} ha confermato di aver inviato il suo Dono di 33€ a {sognatore} (Commento: {commento})',
      ricevuto_dono_ok: 'Hai confermato che il dono è stato Ricevuto',
      entra_in_lavagna: 'Entra sulla Tua Lavagna per vedere le Navi in Partenza',
      doni_ricevuti: 'Doni Ricevuti',
      doni_inviati_da_confermare: 'Doni Inviati (da confermare)',
      doni_mancanti: 'Doni Mancanti',
      temporanea: 'Temporanea',
      nave_provvisoria: 'Ti è stata assegnata una <strong>Nave TEMPORANEA</strong>.<br>E\'normale che vedrai variare la data di partenza, dovuto all\'aggiornamento della graduatoria dei passeggeri.',
      ritessitura: 'RITESSITURA',
    },
    reg: {
      volta: 'volta',
      volte: 'volte',
      registered: 'Registrato',
      contacted: 'Contattato',
      name_complete: 'Nome Completo',
      num_invitati: 'Num.Invitati',
      is_in_whatsapp: 'In Whatsapp',
      is_in_telegram: 'In Telegram',
      cell_complete: 'Cellulare',
      failed: 'Fallito',
      ind_order: 'Num',
      ipaddr: 'IP',
      verified_email: 'Email Verificata',
      reg_lista_prec: 'Inserire il Nome, Cognome e numero di cellulare che avete lasciato in passato quando vi siete iscritti alla Chat!<br>In questo modo il sistema vi riconosce e vi mantiene la posizione della lista.',
      nuove_registrazioni: 'Se questa è una NUOVA registrazione, dovete contattare la persona che vi ha INVITATO, che vi lascerà il LINK CORRETTO per fare la Registrazione sotto di lui/lei',
      you: 'Tu',
      cancella_invitato: 'Elimina Invitato',
      cancella_account: 'Elimina Profilo',
      cancellami: 'Sei sicuro di voler Eliminare completamente la tua Registrazione su {sitename}, uscendo così dal movimento? Non potrai piu\' accedere al sito tramite i tuoi dati, Perderai la tua POSIZIONE e i Tuoi Invitati verranno REGALATI a chi ti ha invitato.',
      cancellami_2: 'ULTIMO AVVISO! Vuoi uscire Definitivamente da {sitename} ?',
      account_cancellato: 'Il tuo Profilo è stato cancellato correttamente',
      regala_invitato: 'Regala Invitato',
      regala_invitante: 'Imposta Invitante',
      messaggio_invito: 'Messaggio di Invito',
      messaggio_invito_msg: 'Invia questo messaggio a tutti coloro a cui vuoi condividere questo Movimento !',
      videointro: 'Video Introduttivo',
      invitato_regalato: 'Invitato Regalato',
      invitante_regalato: 'Invitante Regalato',
      legenda: 'Legenda',
      aportador_solidario: 'Chi ti ha Invitato',
      username_regala_invitato: 'Username del Destinatario del regalo',
      aportador_solidario_nome_completo: 'Nominativo Invitante',
      aportador_solidario_nome_completo_orig: 'Invitante Originario',
      aportador_solidario_ind_order: 'Num Invitante',
      reflink: 'Link da condividere ai tuoi invitati:',
      linkzoom: 'Link per entrare in Zoom:',
      page_title: 'Registrazione',
      made_gift: 'Dono',
      note: 'Note',
      incorso: 'Registrazione in corso...',
      richiesto: 'Campo Richiesto',
      email: 'Email',
      intcode_cell: 'Prefisso Int.',
      cell: 'Cellulare Telegram',
      cellreg: 'Cellulare con cui ti eri registrato',
      nationality: 'Nazionalità',
      email_paypal: 'Email Paypal',
      revolut: 'Revolut',
      link_payment: 'Link Paypal.me',
      note_payment: 'Note Aggiuntive',
      country_pay: 'Paese di Destinazione Pagamenti',
      username_telegram: 'Username Telegram',
      telegram: 'Chat Telegram \'{botname}\'',
      teleg_id: 'Telegram ID',
      teleg_id_old: 'OLD Tel ID',
      teleg_auth: 'Codice Autorizzazione',
      click_per_copiare: 'Cliccaci sopra per copiarlo sugli appunti',
      copia_messaggio: 'Copia Messaggio',
      teleg_torna_sul_bot: '1) Copia il codice cliccando sul bottone qui sopra<br>2) torna su {botname} cliccando qui sotto 👇 ed incolla (o scrivi) il codice',
      teleg_checkcode: 'Codice Telegram',
      my_dream: 'Il mio Sogno',
      saw_and_accepted: 'Condizioni',
      saw_zoom_presentation: 'Ha visto Zoom',
      manage_telegram: 'Gestori Telegram',
      paymenttype: 'Modalità di Pagamenti Disponbili (Revolut)',
      selected: 'Selezionati',
      img: 'Immagine',
      date_reg: 'Data Reg.',
      requirement: 'Requisiti',
      perm: 'Permessi',
      elimina: 'Elimina',
      deleted: 'Nascosto',
      sospeso: 'Sospeso',
      username: 'Username (Pseudonimo)',
      username_short: 'Username',
      name: 'Nome',
      surname: 'Cognome',
      username_login: 'Username o email',
      password: 'Password',
      repeatPassword: 'Ripeti password',
      terms: 'Accetto i termini della privacy',
      onlyadult: 'Confermo di essere Maggiorenne',
      submit: 'Registrati',
      title_verif_reg: 'Verifica Registrazione',
      reg_ok: 'Registrazione Effettuata con Successo',
      verificato: 'Verificato',
      non_verificato: 'Non Verificato',
      forgetpassword: 'Password dimenticata?',
      modificapassword: 'Modifica Password',
      err: {
        required: 'è richiesto',
        email: 'inserire una email valida',
        errore_generico: 'Si prega di compilare correttamente i campi',
        atleast: 'dev\'essere lungo almeno di',
        complexity: 'deve contenere almeno 1 minuscola, 1 maiuscola, 1 cifra',
        notmore: 'non dev\'essere lungo più di',
        char: 'caratteri',
        terms: 'Devi accettare le condizioni, per continuare.',
        email_not_exist: 'l\'Email non è presente in archivio, verificare se è corretta',
        duplicate_email: 'l\'Email è già stata registrata',
        user_already_exist: 'La registrazione con questi dati (nome, cognome e cellulare) è stata già effettuata. Per accedere al sito, cliccare sul bottone LOGIN dalla HomePage.',
        user_extralist_not_found: 'Utente in archivio non trovato, inserire il Nome, Cognome e numero di cellulare comunicato nella lista nel 2019. Se questa è una nuova registrazione, dovete registrarvi tramite il LINK di chi vi sta invitando.',
        user_not_this_aportador: 'Stai utilizzando un link di una persona diversa dal tuo invitato originale.',
        duplicate_username: 'L\'Username è stato già utilizzato',
        username_not_valid: 'L\'Username non é valido',
        aportador_not_exist: 'L\'Username di chi ti ha invitato non è presente. Contattaci.',
        aportador_regalare_not_exist: 'Inserire l\'Username della persona che si vuole regalare l\'invitato',
        invitante_username_not_exist: 'Inserire l\'Username della persona che fa da invitante',
        sameaspassword: 'Le password devono essere identiche',
      },
      tips: {
        email: 'inserisci la tua email',
        username: 'username lunga almeno 6 caratteri',
        password: 'deve contenere 1 minuscola, 1 maiuscola e 1 cifra',
        repeatpassword: 'ripetere la password',

      },
    },
    op: {
      qualification: 'Qualifica',
      usertelegram: 'Username Telegram',
      disciplines: 'Discipline',
      certifications: 'Certificazioni',
      intro: 'Introduzione',
      info: 'Biografia',
      webpage: 'Pagina Web',
      days_working: 'Giorni Lavorativi',
      facebook: 'Pagina Facebook',
    },
    login: {
      page_title: 'Login',
      incorso: 'Login in corso',
      enter: 'Accedi',
      esci: 'Esci',
      errato: 'Username o password errata. Riprovare',
      subaccount: "Questo account è stato accorpato con il vostro Principale. Eseguire l'accesso utilizzando l'username (o email) del PRIMO account.",
      completato: 'Login effettuato!',
      needlogin: 'E\' necessario effettuare il login prima di continuare',
    },
    reset: {
      title_reset_pwd: 'Reimposta la tua Password',
      send_reset_pwd: 'Invia Reimposta la password',
      incorso: 'Richiesta Nuova Email...',
      email_sent: 'Email inviata',
      check_email: 'Controlla la tua email, ti arriverà un messaggio con un link per reimpostare la tua password. Questo link, per sicurezza, scadrà dopo 4 ore.',
      token_scaduto: 'Il token è scaduto oppure è stato già usato. Ripetere la procedura di reset password',
      title_update_pwd: 'Aggiorna la tua password',
      update_password: 'Aggiorna Password',
    },
    logout: {
      uscito: 'Sei Uscito',
    },
    errors: {
      graphql: {
        undefined: 'non definito',
      },
    },
    showbigmap: 'Mostra la mappa più grande',
    todo: {
      titleprioritymenu: 'Priorità:',
      inserttop: 'Inserisci il Task in cima',
      insertbottom: 'Inserisci il Task in basso',
      edit: 'Descrizione Task:',
      completed: 'Ultimi Completati',
      usernotdefined: 'Attenzione, occorre essere Loggati per poter aggiungere un Todo',
      start_date: 'Data Inizio',
      status: 'Stato',
      completed_at: 'Data Completamento',
      expiring_at: 'Data Scadenza',
      phase: 'Fase',
    },
    notification: {
      status: 'Stato',
      ask: 'Attiva le Notifiche',
      waitingconfirm: 'Conferma la richiesta di Notifica',
      confirmed: 'Notifiche Attivate!',
      denied: 'Notifiche Disabilitate! Attenzione così non vedrai arrivarti i messaggi. Riabilitali per vederli.',
      titlegranted: 'Permesso Notifiche Abilitato!',
      statusnot: 'Stato Notifiche',
      titledenied: 'Permesso Notifiche Disabilitato!',
      title_subscribed: 'Sottoscrizione a {sitename}!',
      subscribed: 'Ora potrai ricevere i messaggi e le notifiche.',
      newVersionAvailable: 'Aggiorna',
    },
    connection: 'Connessione',
    proj: {
      newproj: 'Titolo Progetto',
      newsubproj: 'Titolo Sotto-Progetto',
      insertbottom: 'Inserisci Nuovo Project',
      longdescr: 'Descrizione',
      hoursplanned: 'Ore Preventivate',
      hoursadded: 'Ore Aggiuntive',
      hoursworked: 'Ore Lavorate',
      begin_development: 'Inizio Sviluppo',
      begin_test: 'Inizio Test',
      progresstask: 'Progressione',
      actualphase: 'Fase Attuale',
      hoursweeky_plannedtowork: 'Ore settimanali previste',
      endwork_estimate: 'Data fine lavori stimata',
      privacyread: 'Chi lo puo vedere:',
      privacywrite: 'Chi lo puo modificare:',
      totalphases: 'Totale Fasi',
      themecolor: 'Tema Colore',
      themebgcolor: 'Tema Colore Sfondo',
    },
    where: {
      code: 'Id',
      whereicon: 'Icona',
    },
    col: {
      label: 'Etichetta',
      value: 'Valore',
      type: 'Tipo',
    },
    cal: {
      num: 'Numero',
      booked: 'Prenotato',
      booked_error: 'Prenotazione non avvenuta. Riprovare più tardi',
      sendmsg_error: 'Messaggio non inviato. Riprovare più tardi',
      sendmsg_sent: 'Messaggio Inviato',
      booking: 'Prenota Evento',
      titlebooking: 'Prenotazione',
      modifybooking: 'Modifica Prenotazione',
      cancelbooking: 'Cancella Prenotazione',
      canceledbooking: 'Prenotazione Cancellata',
      cancelederrorbooking: 'Cancellazione non effettuata, Riprovare più tardi',
      cancelevent: 'Cancella Evento',
      canceledevent: 'Evento Cancellato',
      cancelederrorevent: 'Cancellazione Evento non effettuata, Riprovare',
      event: 'Evento',
      starttime: 'Dalle',
      nextevent: 'Prossimo Evento',
      readall: 'Leggi tutto',
      enddate: 'al',
      endtime: 'alle',
      duration: 'Durata',
      hours: 'Orario',
      when: 'Quando',
      where: 'Dove',
      teacher: 'Condotto da',
      enterdate: 'Inserisci data',
      details: 'Dettagli',
      infoextra: 'Date e Ora Extra:',
      alldayevent: 'Tutto il giorno',
      eventstartdatetime: 'Inizio',
      enterEndDateTime: 'Fine',
      selnumpeople: 'Partecipanti',
      selnumpeople_short: 'Num',
      msgbooking: 'Messaggio da inviare',
      showpdf: 'Vedi PDF',
      bookingtextdefault: 'Prenoto per',
      bookingtextdefault_of: 'di',
      data: 'Data',
      teachertitle: 'Insegnante',
      peoplebooked: 'Prenotaz.',
      showlastschedule: 'Vedi tutto il Calendario',
    },
    msgs: {
      message: 'Messaggio',
      messages: 'Messaggi',
      nomessage: 'Nessun Messaggio',
    },
    event: {
      _id: 'id',
      typol: 'Typology',
      short_tit: 'Titolo Breve',
      title: 'Titolo',
      details: 'Dettagli',
      bodytext: 'Testo Evento',
      dateTimeStart: 'Data Inizio',
      dateTimeEnd: 'Data Fine',
      bgcolor: 'Colore Sfondo',
      days: 'Giorni',
      icon: 'Icona',
      img: 'Nomefile Immagine',
      img_small: 'Img Piccola',
      where: 'Dove',
      contribtype: 'Tipo Contributo',
      price: 'Contributo',
      askinfo: 'Chiedi Info',
      showpage: 'Vedi Pagina',
      infoafterprice: 'Note dopo la Quota',
      teacher: 'Insegnante', // teacherid
      teacher2: 'Insegnante2', // teacherid2
      infoextra: 'InfoExtra',
      linkpage: 'WebSite',
      linkpdf: 'Link ad un PDF',
      nobookable: 'Non Prenotabile',
      news: 'Novità',
      dupId: 'Id Duplicato',
      canceled: 'Cancellato',
      deleted: 'Eliminato',
      duplicate: 'Duplica',
      notempty: 'Il campo non può essere vuoto',
      modified: 'Modificato',
      showinhome: 'Mostra nella Home',
      showinnewsletter: 'Mostra nella Newsletter',
      color: 'Colore del titolo',
    },
    disc: {
      typol_code: 'Codice Tipologia',
      order: 'Ordinamento',
    },
    newsletter: {
      title: 'Desideri ricevere la nostra Newsletter?',
      name: 'Il tuo Nome',
      surname: 'Il tuo Cognome',
      namehint: 'Nome',
      surnamehint: 'Cognome',
      email: 'La tua Email',
      submit: 'Iscriviti',
      reset: 'Cancella',
      typesomething: 'Compilare correttamente il campo',
      acceptlicense: 'Accetto la licenza e i termini',
      license: 'Devi prima accettare la licenza e i termini',
      submitted: 'Iscritto',
      menu: 'Newsletter1',
      template: 'Modelli Email',
      sendemail: 'Invia',
      check: 'Controlla',
      sent: 'Già Inviate',
      mailinglist: 'Lista Contatti',
      settings: 'Impostazioni',
      serversettings: 'Server',
      others: 'Altro',
      templemail: 'Modello Email',
      datetoSent: 'DataOra Invio',
      activate: 'Attivato',
      numemail_tot: 'Email Totali',
      numemail_sent: 'Email Inviate',
      datestartJob: 'Inizio Invio',
      datefinishJob: 'Fine Invio',
      lastemailsent_Job: 'Ultima Inviata',
      starting_job: 'Invio Iniziato',
      finish_job: 'Invio Terminato',
      processing_job: 'Lavoro in corso',
      error_job: 'Info Errori',
      statesub: 'Sottoscritto',
      wrongerr: 'Email non valida',
    },
    privacy_policy: 'Privacy Policy',
    cookies: 'Usiamo i Cookie per una migliore prestazione web.',
  },
};

export default msg_it;
