export { duplicate } from './duplicate'
export { registereduser } from './registereduser'
export { aportadorexist } from './aportadorexist'
export { registeredemail } from './registeredemail'
export { complexity } from './complexity'
export { alfanum } from './alfanum'
