export * from './logo'
export * from './CMyPage'
export * from './CMyAvatar'
export * from './CTitle'
export * from './CImgTitle'
export * from './BannerCookies'
export * from './testpao'
export * from './Footer'
export * from './FormNewsletter'
export * from './CCopyBtn'
export * from './CCard'
export * from './CCardOperator'
export * from './CCardCarousel'
export * from './CCardDiscipline'
export * from './CMyTeacher'
export * from './CSingleCart'
// export * from './PagePolicy'
// export * from './CFacebookFrame'
// export * from './CPreloadImages'
