export const serv_constants = {
  RIS_CODE_TODO_CREATING_NOTMYUSER: -1001,
  RIS_CODE_NOT_MY_USERNAME: -1010,

  RIS_CODE_ERR: -99,
  RIS_CODE_EMAIL_ALREADY_VERIFIED: -5,
  RIS_CODE_EMAIL_VERIFIED: 1,

  RIS_CODE_USER_NOT_THIS_APORTADOR: -75,
  RIS_CODE_USER_EXTRALIST_NOTFOUND: -70,
  RIS_CODE_USERNAME_ALREADY_EXIST: -60,
  RIS_CODE_USERNAME_NOT_VALID: -65,
  RIS_CODE_EMAIL_ALREADY_EXIST: -50,
  RIS_CODE_USER_ALREADY_EXIST: -48,
  RIS_CODE_EMAIL_NOT_EXIST: -45,
  RIS_CODE_EMAIL_NOT_SENT: -40,
  RIS_CODE_ERR_UNAUTHORIZED: -30,

  RIS_CODE_LOGIN_ERR_GENERIC: -20,
  RIS_CODE_LOGIN_ERR: -10,
  RIS_CODE_LOGIN_ERR_SUBACCOUNT: -8,

  RIS_CODE_OK: 1,
  RIS_CODE_LOGIN_OK: 1,
  RIS_ISCRIZIONE_OK: 5,
  RIS_CODE__HTTP_FORBIDDEN_INVALID_TOKEN: 403,

  RIS_CODE_TOKEN_RESETPASSWORD_NOT_FOUND: -23,

  RIS_SUBSCRIBED_OK: 1,
  RIS_SUBSCRIBED_ALREADYEXIST: 2,
  RIS_SUBSCRIBED_ERR: -1,
  RIS_SUBSCRIBED_STR: 'subscribed',

  RIS_UNSUBSCRIBED_OK: 5,
  RIS_UNSUBSCRIBED_STR: 'unsubscribed',
  RIS_UNSUBSCRIBED_NOT_EXIST: -5,

  LIST_END: '10000000',
  LIST_START: null,

  PREFIX_IMG: 'm_',
  PREFIX_IMG_SMALL: 'sm_',

  Privacy: {
    all: 'all',
    friends: 'friends',
    mygroup: 'mygroup',
    onlyme: 'onlyme',
    inherited: 'inherited'
  },

  TypeProj: {
    TYPE_PROJECT: 1,
    TYPE_SUBDIR: 2,
  }


}
